import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    league:{
        type:String,
        default:"No League"
    },
    correct:{
        type:Number,
        default:0,
    },
    progressMaxNum:{
        type:Number,
        enum:[5,10,20,40],
        default:5
    },
    progressNum:{
        type:Number,
        default:0
    },
    ChemistryBunch:{
        type:Boolean,
        default:false
    },
    chemQuiz1:{
        type:Boolean,
        default:false
    },
    chemQuiz2:{
        type:Boolean,
        default:false
    },
    chemQuiz3:{
        type:Boolean,
        default:false
    },
    chemQuiz4:{
        type:Boolean,
        default:false
    },
    chemQuiz5:{
        type:Boolean,
        default:false
    },
    PhysicsBunch:{
        type:Boolean,
        default:false
    },
    phyQuiz1:{
        type:Boolean,
        default:false
    },
    phyQuiz2:{
        type:Boolean,
        default:false
    },
    phyQuiz3:{
        type:Boolean,
        default:false
    },
    phyQuiz4:{
        type:Boolean,
        default:false
    },
    phyQuiz5:{
        type:Boolean,
        default:false
    },
    MathsBunch:{
        type:Boolean,
        default:false
    },
    mathQuiz1:{
        type:Boolean,
        default:false
    },
    mathQuiz2:{
        type:Boolean,
        default:false
    },
    mathQuiz3:{
        type:Boolean,
        default:false
    },
    mathQuiz4:{
        type:Boolean,
        default:false
    },
    mathQuiz5:{
        type:Boolean,
        default:false
    },
},
{
    timestamps:true
})

export const User = mongoose.model("User",userSchema)